### PR TITLE
Support for ZodArray

### PR DESCRIPTION
**Pull request by merojosa**
Hello! In a project I'm involved we are using this package but we have some endpoints that have arrays as inputs. So this PR enables the support for ZodArray.

I added a test and I also tested the new change in my project (that has quite a few routes and endpoints with complex inputs) and it's working correctly.

Would you mind taking a look and, if you agree, merge it?

### CODE REVIEW

**Review by dtinth — DISMISSED** [review]
one minor change in the test requested. other than that, it looks great! thanks for contributing. 😃

**Comment by merojosa** [comment]
@dtinth I think you didn't submit the requested change comment, I can't see it 🤔

**Comment by dtinth** [comment]
@merojosa Hey, I was overwhelmed with other stuff and didn’t have the bandwidth to properly process this PR. My apologies. I’ll merge this in now and make the fixes I want right afterwards.

Thanks again for the contribution!

**Comment by dtinth** [comment]
Released as v0.2.0

**Pull request merged**
